telegram:
  alert_min_level: WARNING
  bot_token: 8531407014:AAFsKnKlt5w05cL4zRv5771ZbuZJY1gmQHU
  chat_id: '543258309'
  enable_bot: true
  enabled: true
  notify:
    alerts: true
    daily_report: true
    shutdown: true
    startup: true
    trade_closed: true
    trade_opened: true
